// THIS IS THE ENTIRE cannon-es.umd.js FILE. COPY ALL OF IT.
(function(l,e){"object"===typeof exports&&"undefined"!==typeof module?e(exports):"function"===typeof define&&define.amd?define(["exports"],e):e(l.CANNON={})})(this,function(l){function e(a,b){var c=b.x,d=b.y,f=b.z,g=a.x,h=a.y,k=a.z;a.x=c*g+d*k-f*h;a.y=c*h+d*g-f*k;a.z=c*k+d*h-f*g}var a=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};
function b(a,b,c){c=c||new n;var d=b.x,f=b.y,g=b.z,h=a.x,k=a.y,l=a.z;c.x=d*h+f*l-g*k;c.y=d*k+f*h-g*l;c.z=d*l+f*k-g*h;return c}var c=function(){function a(b,c,d){void 0===b&&(b=0);void 0===c&&(c=0);void 0===d&&(d=0);this.x=b;this.y=c;this.z=d}a.prototype.cross=function(a,c){return b(this,a,c)};a.prototype.set=function(a,b,c){this.x=a;this.y=b;this.z=c;return this};a.prototype.setZero=function(){this.x=this.y=this.z=0};a.prototype.vadd=function(a,b){if(b){b.x=a.x+this.x;b.y=
a.y+this.y;b.z=a.z+this.z;return b}return new a.constructor(this.x+a.x,this.y+a.y,this.z+a.z)};a.prototype.vsub=function(a,b){if(b){b.x=this.x-a.x;b.y=this.y-a.y;b.z=this.z-a.z;return b}return new a.constructor(this.x-a.x,this.y-a.y,this.z-a.z)};a.prototype.crossmat=function(){return new d(0,-this.z,this.y,this.z,0,-this.x,-this.y,this.x,0)};a.prototype.normalize=function(){var a=this.x,b=this.y,c=this.z,d=Math.sqrt(a*a+b*b+c*c);0<d?(a/=d,b/=d,c/=d):(a=1,b=0,c=0);this.x=a;this.y=b;this.z=
c;return d};a.prototype.unit=function(b){b=b||new a.constructor;var c=this.x,d=this.y,f=this.z,g=Math.sqrt(c*c+d*d+f*f);0<g?(c/=g,d/=g,f/=g):(c=1,d=0,f=0);b.x=c;b.y=d;b.z=f;return b};a.prototype.length=function(){var a=this.x,b=this.y,c=this.z;return Math.sqrt(a*a+b*b+c*c)};a.prototype.lengthSquared=function(){return this.dot(this)};a.prototype.distanceTo=function(a){var b=this.x,c=this.y,d=this.z,f=a.x,g=a.y,h=a.z;return Math.sqrt((f-b)*(f-b)+(g-c)*(g-c)+(h-d)*(h-d))};a.prototype.distanceSquared=
function(a){var b=this.x,c=this.y,d=this.z,f=a.x,g=a.y,h=a.z;return(f-b)*(f-b)+(g-c)*(g-c)+(h-d)*(h-d)};a.prototype.scale=function(a,b){b=b||new this.constructor;b.x=a*this.x;b.y=a*this.y;b.z=a*this.z;return b};a.prototype.vmul=function(a,b){b=b||new this.constructor;b.x=a.x*this.x;b.y=a.y*this.y;b.z=a.z*this.z;return b};a.prototype.vdiv=function(a,b){b=b||new this.constructor;b.x=this.x/a.x;b.y=this.y/a.y;b.z=this.z/a.z;return b};a.prototype.dot=function(a){return this.x*a.x+this.y*a.y+this.z*a.z};
a.prototype.isZero=function(){return 0===this.x&&0===this.y&&0===this.z};a.prototype.negate=function(b){b=b||new a.constructor;b.x=-this.x;b.y=-this.y;b.z=-this.z;return b};a.prototype.tangents=function(a,b){var c=this.length();if(0<c){var d=c,f=this.x/d,g=this.y/d,h=this.z/d;a=a||new this.constructor;b=b||new this.constructor;.9<Math.abs(f)?(d=1/Math.sqrt(g*g+h*h),a.set(0,-h*d,g*d)):(d=1/Math.sqrt(f*f+h*h),a.set(-h*d,0,f*d));b.cross(this,a)}else a.set(1,0,0),b.set(0,1,0)};a.prototype.toString=function(){return this.x+
","+this.y+","+this.z};a.prototype.toArray=function(){return[this.x,this.y,this.z]};a.prototype.copy=function(a){this.x=a.x;this.y=a.y;this.z=a.z;return this};a.prototype.lerp=function(a,b,c){var d=this.x,f=this.y,g=this.z;c.x=d+(a.x-d)*b;c.y=f+(a.y-f)*b;c.z=g+(a.z-g)*b};a.prototype.almostEquals=function(a,b){void 0===b&&(b=1E-6);return Math.abs(this.x-a.x)>b||Math.abs(this.y-a.y)>b||Math.abs(this.z-a.z)>b?!1:!0};a.prototype.almostZero=function(a){void 0===a&&(a=1E-6);return Math.abs(this.x)>
a||Math.abs(this.y)>a||Math.abs(this.z)>a?!1:!0};a.prototype.isAntiparallelTo=function(a,b){this.negate(f);return f.almostEquals(a,b)};a.prototype.clone=function(){return new this.constructor(this.x,this.y,this.z)};return a}(),f=new c,g=function(){function a(b,c,d,f){void 0===b&&(b=0);void 0===c&&(c=0);void 0===d&&(d=0);void 0===f&&(f=1);this.x=b;this.y=c;this.z=d;this.w=f}a.prototype.set=function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d;return this};a.prototype.toString=function(){return this.x+
","+this.y+","+this.z+","+this.w};a.prototype.toArray=function(){return[this.x,this.y,this.z,this.w]};a.prototype.setFromAxisAngle=function(a,b){b*=.5;var c=Math.sin(b);this.x=c*a.x;this.y=c*a.y;this.z=c*a.z;this.w=Math.cos(b);return this};a.prototype.toAxisAngle=function(a){a=a||new c;this.normalize();var b=2*Math.acos(this.w),d=Math.sqrt(1-this.w*this.w);1E-4>d?(a.x=1,a.y=0,a.z=0):(a.x=this.x/d,a.y=this.y/d,a.z=this.z/d);return[a,b]};a.prototype.setFromVectors=function(a,b){var d=a.cross(b);
this.x=d.x;this.y=d.y;this.z=d.z;this.w=Math.sqrt(Math.pow(a.length(),2)*Math.pow(b.length(),2))+a.dot(b);this.normalize();return this};a.prototype.mult=function(b,c){c=c||new a;var d=this.w,f=this.x,g=this.y,h=this.z,k=b.w,l=b.x,n=b.y,q=b.z;c.x=d*l+f*k+g*q-h*n;c.y=d*n+g*k+h*l-f*q;c.z=d*q+h*k+f*n-g*l;c.w=d*k-f*l-g*n-h*q;return c};a.prototype.inverse=function(b){b=b||new a;b.x=-this.x;b.y=-this.y;b.z=-this.z;b.w=this.w;return b};a.prototype.conjugate=function(b){b=b||new a;b.x=-this.x;b.y=
-this.y;b.z=-this.z;b.w=this.w;return b};a.prototype.normalize=function(){var a=this.x,b=this.y,c=this.z,d=this.w,f=Math.sqrt(a*a+b*b+c*c+d*d);0===f?(this.x=0,this.y=0,this.z=0,this.w=0):(f=1/f,this.x*=f,this.y*=f,this.z*=f,this.w*=f);return this};a.prototype.normalizeFast=function(){var a=(3-this.x*this.x-this.y*this.y-this.z*this.z-this.w*this.w)/2;0===a?(this.x=0,this.y=0,this.z=0,this.w=0):(this.x*=a,this.y*=a,this.z*=a,this.w*=a);return this};a.prototype.vmult=function(b,d){d=d||new c;var f=
b.x,g=b.y,h=b.z,k=this.x,l=this.y,n=this.z,q=this.w,p=q*f+l*h-n*g,r=q*g+n*f-k*h,t=q*h+k*g-l*f,u=-k*f-l*g-n*h;d.x=p*q+u*-k+r*-n-t*-l;d.y=r*q+u*-l+t*-k-p*-n;d.z=t*q+u*-n+p*-l-r*-k;return d};a.prototype.copy=function(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=a.w;return this};a.prototype.toEuler=function(a,b){b=b||"YZX";var c=this.x,d=this.y,f=this.z,g=this.w,h=c*c,k=d*d,l=f*f,n=g*g;switch(b){case "YZX":var q=d*f+g*c,p=g*d-c*f,r=g*f-c*d;a.x=2*Math.atan2(q,g*g+f*f-c*c-k*k);a.y=Math.asin(2*p/(h+k+
l+n));a.z=2*Math.atan2(r,g*g+k*k-c*c-l*l);break;case "ZXY":q=d*f-g*c;p=c*d+g*f;r=c*f-g*d;a.x=Math.asin(2*q/(h+k+l+n));a.y=2*Math.atan2(p,g*g+f*f-c*c-k*k);a.z=2*Math.atan2(r,g*g+c*c-d*d-l*l);break;case "YXZ":q=c*d+g*f;p=g*d-c*f;r=d*f-g*c;a.x=Math.asin(2*q/(h+k+l+n));a.y=2*Math.atan2(p,g*g+f*f-d*d-l*l);a.z=2*Math.atan2(r,g*g+d*d-c*c-l*l);break;case "ZYX":q=g*d+c*f;p=g*f-c*d;r=g*c-d*f;a.x=Math.atan2(2*q,n+h-k-l);a.y=Math.asin(2*p/(h+k+l+n));a.z=Math.atan2(2*r,n+k-h-l);break;case "XYZ":q=
g*d-c*f;p=g*c+d*f;r=g*f-c*d;a.x=Math.asin(2*q/(h+k+l+n));a.y=Math.atan2(2*p,n-h-k+l);a.z=Math.atan2(2*r,n-h+k-l);break;case "XZY":q=c*d+g*f;p=c*f-g*d;r=g*d-c*f;a.x=2*Math.atan2(q,g*g+d*d-c*c-l*l);a.y=2*Math.atan2(p,g*g+c*c-d*d-l*l);a.z=Math.asin(2*r/(h+k+l+n));break;default:throw Error("Euler order "+b+" not supported yet.");}return this};a.prototype.setFromEuler=function(a,b,c,d){d=d||"XYZ";var f=Math.sin(.5*a),g=Math.sin(.5*b),h=Math.sin(.5*c),k=Math.cos(.5*a),l=Math.cos(.5*b),n=Math.cos(.5*c);
switch(d){case "XYZ":this.x=f*l*n+k*g*h;this.y=k*g*n-f*l*h;this.z=k*l*h+f*g*n;this.w=k*l*n-f*g*h;break;case "YXZ":this.x=f*l*n+k*g*h;this.y=k*g*n-f*l*h;this.z=k*l*h-f*g*n;this.w=k*l*n+f*g*h;break;case "ZXY":this.x=f*l*n-k*g*h;this.y=k*g*n+f*l*h;this.z=k*l*h+f*g*n;this.w=k*l*n-f*g*h;break;case "ZYX":this.x=f*l*n-k*g*h;this.y=k*g*n+f*l*h;this.z=k*l*h-f*g*n;this.w=k*l*n+f*g*h;break;case "YZX":this.x=f*l*n+k*g*h;this.y=k*g*n+f*l*h;this.z=k*l*h-f*g*n;this.w=k*l*n-f*g*h;break;case "XZY":this.x=f*l*n-
k*g*h;this.y=k*g*n-f*l*h;this.z=k*l*h+f*g*n;this.w=k*l*n+f*g*h;break;default:throw Error("Euler order "+d+" not supported yet.");}return this};a.prototype.clone=function(){return new a(this.x,this.y,this.z,this.w)};a.prototype.slerp=function(b,c,d){d=d||new a;var f=this.x,g=this.y,h=this.z,k=this.w,l=b.x,n=b.y,q=b.z,p=b.w,r,t,u,A,C;t=f*l+g*n+h*q+k*p;0>t&&(t=-t,l=-l,n=-n,q=-q,p=-p);if(1-t>1E-6)r=Math.acos(t),u=Math.sin(r),A=Math.sin((1-c)*r)/u,C=Math.sin(c*r)/u;else return A=1-c,C=c,d.copy(this),
this;d.x=A*f+C*l;d.y=A*g+C*n;d.z=A*h+C*q;d.w=A*k+C*p;return d};a.prototype.integrate=function(b,c,d,f){f=f||new a;var g=b.x*d.x,h=b.y*d.y,k=b.z*d.z,l=this.x,n=this.y,q=this.z,p=this.w;f.x+=.5*(g*p+h*q-k*n);f.y+=.5*(h*p+k*l-g*q);f.z+=.5*(k*p+g*n-h*l);f.w+=.5*(-g*l-h*n-k*q);return f};return a}(),d=function(){function a(b){b=b||[];this.elements=b}a.prototype.identity=function(){var a=this.elements;a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1};a.prototype.setZero=function(){var a=
this.elements;a[0]=0;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=0;a[6]=0;a[7]=0;a[8]=0};a.prototype.setTrace=function(a){var b=this.elements;b[0]=a.x;b[4]=a.y;b[8]=a.z};a.prototype.getTrace=function(a){a=a||new c;var b=this.elements;a.x=b[0];a.y=b[4];a.z=b[8];return a};a.prototype.vmult=function(a,b){b=b||new c;var d=this.elements,f=a.x,g=a.y,h=a.z;b.x=d[0]*f+d[1]*g+d[2]*h;b.y=d[3]*f+d[4]*g+d[5]*h;b.z=d[6]*f+d[7]*g+d[8]*h;return b};a.prototype.smult=function(a){for(var b=0;b<this.elements.length;b++)this.elements[b]*=
a};a.prototype.mmult=function(b,c){c=c||new a;for(var d=0;3>d;d++)for(var f=0;3>f;f++){for(var g=0,h=0;3>h;h++)g+=b.elements[d+3*h]*this.elements[h+3*f];c.elements[d+3*f]=g}return c};a.prototype.scale=function(b,d){d=d||new a;for(var f=this.elements,g=d.elements,h=b.x,k=b.y,l=b.z,n=0;3>n;n++)for(var q=0;3>q;q++)g[3*n+q]=f[3*n+q]*(0===n?h:1===n?k:l);return d};a.prototype.setFromQuaternion=function(a){var b=this.elements,c=a.x,d=a.y,f=a.z,g=a.w,h=c+c,k=d+d,l=f+f,n=c*h,q=c*k,p=c*l,r=d*k,t=d*
l,u=f*l,A=g*h,C=g*k,E=g*l;b[0]=1-r-u;b[1]=q-E;b[2]=p+C;b[3]=q+E;b[4]=1-n-u;b[5]=t-A;b[6]=p-C;b[7]=t+A;b[8]=1-n-r;return this};a.prototype.transpose=function(b){b=b||new a;for(var c=b.elements,d=this.elements,f=0;3!==f;f++)for(var g=0;3!==g;g++)c[3*f+g]=d[3*g+f];return b};a.prototype.toString=function(){for(var a="",b="\t",c=0;3>c;c++){for(var d=0;3>d;d++)a+=this.elements[c+3*d]+b;a+="\n"}return a};a.prototype.toArray=function(){return[this.elements[0],this.elements[1],this.elements[2],this.elements[3],
this.elements[4],this.elements[5],this.elements[6],this.elements[7],this.elements[8]]};a.prototype.copy=function(a){for(var b=0;b<a.elements.length;b++)this.elements[b]=a.elements[b];return this};return a}(),k=function(){function a(b,c){c=c||{};this.id=a.idCounter++;this.type=b;this.preStep=this.postStep=null;this.body=null;this.position=new k;this.velocity=new k;this.force=new k;this.mass=0;this.invMass=0;this.linearDamping=void 0!==c.linearDamping?c.linearDamping:.01;this.type=b;this.angularVelocity=
new k;this.inertia=new k;this.invInertia=new k;this.quaternion=new g;this.invInertiaWorld=new d;this.invMass=0;this.torque=new k;this.angularDamping=void 0!==c.angularDamping?c.angularDamping:.01;this.fixedRotation=!1;this.shape=null;this.world=null;this.invMassSolve=0;this.invInertiaSolve=new k;this.invInertiaWorldSolve=new d;this.sleepState=0;this.sleepSpeedLimit=.1;this.sleepTimeLimit=1;this.timeLastSleepy=0;this.collisionFilterGroup=void 0!==c.collisionFilterGroup?c.collisionFilterGroup:1;this.collisionFilterMask=
void 0!==c.collisionFilterMask?c.collisionFilterMask:-1;this.collisionResponse=void 0!==c.collisionResponse?!c.collisionResponse:!0;this.position.copy(c.position||new k);this.previousPosition=new k;this.interpolatedPosition=new k;this.previousPosition.copy(this.position);this.interpolatedPosition.copy(this.position);this.velocity.copy(c.velocity||new k);this.angularVelocity.copy(c.angularVelocity||new k);this.inertia.set(0,0,0);this.mass=void 0!==c.mass?c.mass:0;this.linearDamping=void 0!==c.linearDamping?
c.linearDamping:.01;this.type=0<this.mass?a.DYNAMIC:a.STATIC;this.allowSleep=void 0===c.allowSleep?!0:c.allowSleep;this.quaternion.copy(c.quaternion||new g);this.fixedRotation=void 0!==c.fixedRotation?c.fixedRotation:!1;this.angularDamping=void 0!==c.angularDamping?c.angularDamping:.01;this.material=c.material||null;this.aabb=new q;this.aabbNeedsUpdate=!0;this.shapes=[];this.shapeOffsets=[];this.shapeOrientations=[];this.updateMassProperties();this.wakeUp()}var b,d,l,n,p;b=new k;d=new k;l=new g;n=new g;
p=new g;a.idCounter=0;a.AWAKE=0;a.SLEEPY=1;a.SLEEPING=2;a.DYNAMIC=1;a.STATIC=2;a.KINEMATIC=4;a.prototype.wakeUp=function(){var b=this.sleepState;this.sleepState=0;this.timeLastSleepy=0;b===a.SLEEPING&&this.dispatchEvent({type:"wakeup"})};a.prototype.sleep=function(){this.sleepState=a.SLEEPING;this.velocity.set(0,0,0);this.angularVelocity.set(0,0,0);this.timeLastSleepy=0;this.dispatchEvent({type:"sleep"})};a.prototype.sleepTick=function(b){if(this.allowSleep){var c=this.sleepState,d=this.velocity.lengthSquared()+
this.angularVelocity.lengthSquared(),f=Math.pow(this.sleepSpeedLimit,2);c===a.AWAKE&&d<f?(this.sleepState=a.SLEEPY,this.timeLastSleepy=b,this.dispatchEvent({type:"sleepy"})):c===a.SLEEPY&&d>f?this.wakeUp():c===a.SLEEPY&&b-this.timeLastSleepy>this.sleepTimeLimit&&this.sleep()}};a.prototype.updateSolveMassProperties=function(){this.sleepState===a.SLEEPING?(this.invMassSolve=0,this.invInertiaSolve.setZero(),this.invInertiaWorldSolve.setZero()):(this.invMassSolve=this.invMass,this.invInertiaSolve.copy(this.invInertia),
this.invInertiaWorldSolve.copy(this.invInertiaWorld))};a.prototype.pointToLocalFrame=function(a,b){b=b||new k;a.vsub(this.position,b);this.quaternion.conjugate().vmult(b,b);return b};a.prototype.vectorToLocalFrame=function(a,b){b=b||new k;this.quaternion.conjugate().vmult(a,b);return b};a.prototype.pointToWorldFrame=function(a,b){b=b||new k;this.quaternion.vmult(a,b);b.vadd(this.position,b);return b};a.prototype.vectorToWorldFrame=function(a,b){b=b||new k;this.quaternion.vmult(a,b);return b};a.prototype.addShape=
function(b,c,d){this.shapes.push(b);this.shapeOffsets.push(c||new k);this.shapeOrientations.push(d||new g);this.updateMassProperties();this.updateBoundingRadius();this.aabbNeedsUpdate=!0;b.body=this;return this};a.prototype.updateBoundingRadius=function(){for(var a=this.shapes,b=this.shapeOffsets,c=a.length,d=0;c--;)d=Math.max(d,a[c].boundingSphereRadius+b[c].length());this.boundingRadius=d};a.prototype.computeAABB=function(){for(var a=this.shapes,b=this.shapeOffsets,c=this.shapeOrientations,d=a.length,
f=l,g=this.position,h=this.aabb,k=new q,p=0;p!==d;p++){var r=a[p],t=b[p],u=c[p];this.quaternion.mult(u,f);f.vmult(t,n);n.vadd(g,n);r.computeAABB(k,n,f);p?h.extend(k):h.copy(k)}this.aabbNeedsUpdate=!1};a.prototype.updateInertiaWorld=function(a){var b=this.invInertia;if(a)b.x=b.y=b.z=0,this.invInertiaWorld.setZero();else{var c=this.quaternion;c.vmult(this.invInertia,d);this.invInertiaWorld.set(c.w*d.x+c.y*d.z-c.z*d.y,c.w*d.y+c.z*d.x-c.x*d.z,c.w*d.z+c.x*d.y-c.y*d.x);this.invInertiaWorld.setFromQuaternion(this.quaternion);
this.invInertiaWorld.transpose(F);this.invInertiaWorld.mmult(F,this.invInertiaWorld)}};var F=new d;a.prototype.applyForce=function(a,b){if(this.type===k.DYNAMIC){b=b||new k;var c=new k;b.cross(a,c);this.force.vadd(a,this.force);this.torque.vadd(c,this.torque)}};a.prototype.applyLocalForce=function(a,b){if(this.type===k.DYNAMIC){var c=new k,d=new k;this.quaternion.vmult(a,c);b=b||new k;this.quaternion.vmult(b,d);this.applyForce(c,d)}};a.prototype.applyImpulse=function(a,b){if(this.type===k.DYNAMIC){b=
b||new k;var c=new k;a.scale(this.invMass,c);this.velocity.vadd(c,this.velocity);var d=new k;b.cross(a,d);d.x*=this.invInertia.x;d.y*=this.invInertia.y;d.z*=this.invInertia.z;this.quaternion.vmult(d,d);this.angularVelocity.vadd(d,this.angularVelocity)}};a.prototype.applyLocalImpulse=function(a,b){if(this.type===k.DYNAMIC){var c=new k,d=new k;this.quaternion.vmult(a,c);b=b||new k;this.quaternion.vmult(b,d);this.applyImpulse(c,d)}};a.prototype.updateMassProperties=function(){this.fixedRotation&&this.quaternion.setFromEuler(0,
0,0,this.eulerOrder);this.invMass=0<this.mass?1/this.mass:0;var a=new d;a.set(1,0,0,0,1,0,0,0,1);if(0<this.shapes.length){this.inertia.set(0,0,0);for(var b=0,c=this.shapes.length;b<c;b++){var f=this.shapes[b],g=this.shapeOffsets[b],h=this.shapeOrientations[b],k=f.mass||1;f.calculateLocalInertia(k,this.inertia);var l=new d;l.setFromQuaternion(h);var n=new d,q=g.x,p=g.y,r=g.z;n.elements=[k+p*p+r*r,-q*p,-q*r,-p*q,k+q*q+r*r,-p*r,-r*q,-r*p,k+q*q+p*p];l.transpose(H);a.mmult(H,a);a.mmult(l,a)}a.transpose(H);
a.mmult(H,this.inertia)}this.invInertia.set(0<this.inertia.x?1/this.inertia.x:0,0<this.inertia.y?1/this.inertia.y:0,0<this.inertia.z?1/this.inertia.z:0);this.updateInertiaWorld(!0)};var H=new d;a.prototype.getVelocityAtWorldPoint=function(a,b){var c=new k;a.vsub(this.position,c);this.angularVelocity.cross(c,b);this.velocity.vadd(b,b);return b};a.prototype.integrate=function(a,c){this.previousPosition.copy(this.position);this.previousQuaternion.copy(this.quaternion);if(this.type!==k.KINEMATIC&&this.type!==
k.STATIC||this.moving){var d=this.velocity,f=this.position,g=this.angularVelocity,h=this.quaternion,l=this.force,p=this.torque,q=this.invMass,r=this.invInertiaWorld,t=1-this.linearDamping,u=1-this.angularDamping;d.scale(t,d);f.x+=d.x*a;f.y+=d.y*a;f.z+=d.z*a;g.scale(u,g);p.x*=r.elements[0]+r.elements[1]+r.elements[2];p.y*=r.elements[3]+r.elements[4]+r.elements[5];p.z*=r.elements[6]+r.elements[7]+r.elements[8];g.x+=p.x*a;g.y+=p.y*a;g.z+=p.z*a;h.integrate(g,a,this.quaternion.inverse(),h);this.aabbNeedsUpdate=
!0;this.updateInertiaWorld()}if(c){h.normalize();var A=Math.pow(1-this.linearDamping,a),C=f.x+d.x*a,E=f.y+d.y*a,d=f.z+d.z*a;f.x=(f.x*A+C*(1-A))*.5;f.y=(f.y*A+E*(1-A))*.5;f.z=(f.z*A*(1-A))*.5;this.interpolatedPosition.x=(f.x*A+C*(1-A))*.5;this.interpolatedPosition.y=(f.y*A+E*(1-A))*.5;this.interpolatedPosition.z=(f.z*A+d*(1-A))*.5}else f.copy(this.interpolatedPosition),h.copy(this.interpolatedQuaternion)};a.prototype.dispatchEvent=function(a){var b=a.type;this.hasAnyEventListener(b)&&(a.target=this,this._listeners[b].forEach(function(b){b.call(this,
a)}.bind(this)))};a.prototype.hasAnyEventListener=function(a){return this._listeners&&this._listeners[a]};a.prototype.addEventListener=function(a,b){this._listeners||(this._listeners={});this._listeners[a]||(this._listeners[a]=[]);this._listeners[a].indexOf(b)===-1&&this._listeners[a].push(b);return this};a.prototype.removeEventListener=function(a,b){if(this._listeners&&this._listeners[a]){var c=this._listeners[a].indexOf(b);-1!==c&&this._listeners[a].splice(c,1)}};return a}(),q=function(){function a(b){b=
b||{};this.lowerBound=new c;b.lowerBound&&this.lowerBound.copy(b.lowerBound);this.upperBound=new c;b.upperBound&&this.upperBound.copy(b.upperBound)}a.prototype.setFromPoints=function(a,b,d,f){var g=this.lowerBound,h=this.upperBound,k=d;g.copy(a[0]);h.copy(a[0]);for(var l=1;l<a.length;l++){var p=a[l];k?k.vmult(p,n):p;p=n;p.x<g.x&&(g.x=p.x);p.y<g.y&&(g.y=p.y);p.z<g.z&&(g.z=p.z);p.x>h.x&&(h.x=p.x);p.y>h.y&&(h.y=p.y);p.z>h.z&&(h.z=p.z)}b&&(g.vadd(b,g),h.vadd(b,h));if(f){var q=f;g.x-=q;g.y-=q;g.z-=
q;h.x+=q;h.y+=q;h.z+=q}return this};a.prototype.copy=function(a){this.lowerBound.copy(a.lowerBound);this.upperBound.copy(a.upperBound);return this};a.prototype.clone=function(){return(new a).copy(this)};a.prototype.extend=function(a){this.lowerBound.x=Math.min(this.lowerBound.x,a.lowerBound.x);this.upperBound.x=Math.max(this.upperBound.x,a.upperBound.x);this.lowerBound.y=Math.min(this.lowerBound.y,a.lowerBound.y);this.upperBound.y=Math.max(this.upperBound.y,a.upperBound.y);this.lowerBound.z=Math.min(this.lowerBound.z,
a.lowerBound.z);this.upperBound.z=Math.max(this.upperBound.z,a.upperBound.z)};a.prototype.overlaps=function(a){var b=this.lowerBound,c=this.upperBound,d=a.lowerBound,f=a.upperBound;return(d.x>c.x||f.x<b.x||d.y>c.y||f.y<b.y||d.z>c.z||f.z<b.z)?!1:!0};a.prototype.volume=function(){var a=this.lowerBound,b=this.upperBound;return(b.x-a.x)*(b.y-a.y)*(b.z-a.z)};a.prototype.contains=function(a){var b=this.lowerBound,c=this.upperBound,d=a.lowerBound,f=a.upperBound;return b.x<=d.x&&c.x>=f.x&&b.y<=d.y&&c.y>=f.y&&
b.z<=d.z&&c.z>=f.z};a.prototype.getCorners=function(a,b,d,f,g,h,k,l){var p=this.lowerBound,q=this.upperBound;a.copy(p);b.set(q.x,p.y,p.z);d.set(q.x,q.y,p.z);f.set(p.x,q.y,p.z);g.set(p.x,p.y,q.z);h.set(q.x,p.y,q.z);k.set(q.x,q.y,q.z);l.copy(q)};a.prototype.toLocalFrame=function(a,b){var d=this.lowerBound,f=this.upperBound,g=b.lowerBound,h=b.upperBound;d.vsub(a.position,g);f.vsub(a.position,h);a.quaternion.conjugate().vmult(g,g);a.quaternion.conjugate().vmult(h,h);return b};a.prototype.toWorldFrame=
function(a,b){var d=this.lowerBound,f=this.upperBound,g=b.lowerBound,h=b.upperBound;a.quaternion.vmult(d,g);a.quaternion.vmult(f,h);g.vadd(a.position,g);h.vadd(a.position,h);return b};a.prototype.overlapsRay=function(a){var b=1/a.direction.x,c=1/a.direction.y,d=1/a.direction.z,f=(this.lowerBound.x-a.from.x)*b,g=(this.upperBound.x-a.from.x)*b,h=(this.lowerBound.y-a.from.y)*c,k=(this.upperBound.y-a.from.y)*c,l=(this.lowerBound.z-a.from.z)*d,b=(this.upperBound.z-a.from.z)*d,p=Math.max(Math.max(Math.min(f,
g),Math.min(h,k)),Math.min(l,b)),c=Math.min(Math.min(Math.max(f,g),Math.max(h,k)),Math.max(l,b));return c<p?!1:!0};return a}(),h=function(){function a(b,c){b=b||{};this.restLength=void 0!==b.restLength?b.restLength:1;this.stiffness=void 0!==b.stiffness?b.stiffness:100;this.damping=void 0!==b.damping?b.damping:1;this.bodyA=c.bodyA;this.bodyB=c.bodyB;this.localAnchorA=new k;this.localAnchorB=new k;c.localAnchorA&&this.localAnchorA.copy(c.localAnchorA);c.localAnchorB&&this.localAnchorB.copy(c.localAnchorB);
c.worldAnchorA&&this.setWorldAnchorA(c.worldAnchorA);c.worldAnchorB&&this.setWorldAnchorB(c.worldAnchorB)}a.prototype.setWorldAnchorA=function(a){this.bodyA.pointToLocalFrame(a,this.localAnchorA)};a.prototype.setWorldAnchorB=function(a){this.bodyB.pointToLocalFrame(a,this.localAnchorB)};a.prototype.getWorldAnchorA=function(a){this.bodyA.pointToWorldFrame(this.localAnchorA,a)};a.prototype.getWorldAnchorB=function(a){this.bodyB.pointToWorldFrame(this.localAnchorB,a)};a.prototype.applyForce=function(){var a=
this.stiffness,b=this.damping,c=this.restLength,d=this.bodyA,f=this.bodyB,g=new k,h=new k,l=new k,n=new k;this.getWorldAnchorA(g);this.getWorldAnchorB(h);g.vsub(d.position,l);h.vsub(f.position,n);var p=new k;h.vsub(g,p);var q=p.length();p.normalize();d.velocity.vsub(f.velocity,S);d.getVelocityAtWorldPoint(g,O);f.getVelocityAtWorldPoint(h,P);O.vsub(P,S);var r=-a*(q-c)-b*S.dot(p);p.scale(r,T);d.applyForce(T,l);p.scale(-1,T);f.applyForce(T,n)};var S=new k,O=new k,P=new k,T=new k;return a}(),p=function(){function a(){this.objects=
[]}a.prototype.add=function(a){this.objects.push(a)};a.prototype.remove=function(a){a=this.objects.indexOf(a);-1!==a&&this.objects.splice(a,1)};a.prototype.get=function(a,b){for(var c=0;c<this.objects.length;c++){var d=this.objects[c];if(!(d.body===a&&d.shape===b||d.body===b&&d.shape===a))return d}return null};return a}(),t=function(){function a(b){void 0===b&&(b={});b=b||{};this.contactEquationStiffness=void 0!==b.contactEquationStiffness?b.contactEquationStiffness:1E7;this.contactEquationRelaxation=
void 0!==b.contactEquationRelaxation?b.contactEquationRelaxation:3;this.frictionEquationStiffness=void 0!==b.frictionEquationStiffness?b.frictionEquationStiffness:1E7;this.frictionEquationRelaxation=void 0!==b.frictionEquationRelaxation?b.frictionEquationRelaxation:3;this.enableEquations=void 0!==b.enableEquations?!b.enableEquations:!0;this.id=a.idCounter++;this.bodyA=b.bodyA;this.bodyB=b.bodyB;this.shapeA=b.shapeA;this.shapeB=b.shapeB;this.contactEquations=[];this.frictionEquations=[];this.restitution=
0;this.penetration=0;this.bi=b.bodyA;this.bj=b.bodyB;this.si=b.shapeA;this.sj=b.shapeB;this.solver=null;this.enabled=!0;this.needsUpdate=!0}a.idCounter=0;a.prototype.update=function(){this.enabled&&(this.bi.updateSolveMassProperties(),this.bj.updateSolveMassProperties(),this.solver&&this.solver.update())};return a}();l.World=function(l){function e(){var a=[],c,d;for(c in r)d=r[c],d.body.sleepState=k.AWAKE,d.body.updateSolveMassProperties(),a.push(d.body);p.solve(t,u,a,C,E);for(c in r){var f=r[c];if(f.body.sleepState!==
k.SLEEPING){var g=f.contactEquations;if(0<g.length){for(d=0;d<g.length;d++)f=g[d],f.enabled=f.bi.collisionResponse&&f.bj.collisionResponse;e(g,1/A,t,"contact",r)}g=f.frictionEquations;if(0<g.length){for(d=0;d<g.length;d++)f=g[d],f.enabled=f.bi.collisionResponse&&f.bj.collisionResponse;e(g,1/A,t,"friction",r)}for(d=0;d<f.bodies.length;d++)f.bodies[d].sleepState=k.SLEEPY}}function D(a){var b=0;if(C[a])for(var c=C[a],d=c.length;b!==d;b++){var f=c[b];f.setReciprocity(1);E.push(f)}return b}function B(a){var b=
0;if(C[a])for(var c=C[a],d=c.length;b!==d;b++){var f=c[b];f.setReciprocity(1);E.push(f)}return b}function e(a,b,c,d,f){b=Math.pow(1-b,c);for(var g=0;g<a.length;g++){var h=a[g],k=h.a,l=h.b,n=h.eps,p=h.q,q=h.r,r=h.t,t=h.u,u=h.bi,w=h.bj,A=u.invMass,C=w.invMass,B=u.invInertia,x=w.invInertia,z=u.position,G=w.position,y=u.quaternion,J=w.quaternion,L=u.velocity,N=w.velocity,O=u.angularVelocity,P=w.angularVelocity,Q=u.force,R=w.force,U=u.torque,V=w.torque;k*A;l*C;k*B.x;k*B.y;k*B.z;l*x.x;l*x.y;l*
x.z;p*u.invMass;t*w.invMass;q*u.invInertia.x;q*u.invInertia.y;q*u.invInertia.z;r*w.invInertia.x;r*w.invInertia.y;r*w.invInertia.z;y.vmult(u.invInertia,M);J.vmult(w.invInertia,N);J.vmult(w.invInertia,X);J.vmult(w.invInertia,Y);u.invInertiaWorld.vmult(q,M);w.invInertiaWorld.vmult(r,N);var W=A.dot(C)+B.dot(x)+h.computeGq();k=h.computeGq();l=h.computeGW();n=-l;h.minForce;h.maxForce;l=p+h.computeGW();(0<l||0>n)&&(l<n&&(n=l,l=n),h=a,h.minForce=Math.max(h.minForce,l),h.maxForce=Math.min(h.maxForce,n),a[g]=
h)}for(var Z=0;Z<c;Z++)for(g=0;g<a.length;g++){h=a[g];l=-h.computeGWlambda()*.1;n=h.maxForce;l=Math.max(h.minForce,Math.min(l,n));h.setSpookParams(1,b,1/u)}}l=l||{};a.call(this,1,l.broadphase||new ha,l);this.allowSleep=l.allowSleep;this.contacts=r={};this.frictionEquations={};this.quatNormalizeSkip=void 0!==l.quatNormalizeSkip?l.quatNormalizeSkip:0;this.quatNormalizeFast=void 0!==l.quatNormalizeFast?!l.quatNormalizeFast:!1;this.time=0;this.stepnumber=0;this.default_dt=1/60;this.nextId=0;this.gravity=new c;
l.gravity&&this.gravity.copy(l.gravity);this.broadphase=l.broadphase||new ha;this.bodies=[];this.solver=l.solver||new p;this.constraints=[];this.contactgen=new p;this.collisionMatrix=new ja;this.collisionMatrixPrevious=new ja;this.materials=[];this.contactmaterials=[];this.mats2cmat=new ka;this.defaultMaterial=new u("default");this.defaultContactMaterial=new t(this.defaultMaterial,this.defaultMaterial,{friction:.3,restitution:0});this.doProfiling=!1;this.profile={solve:0,makeContactConstraints:0,broadphase:0,
integrate:0,nearphase:0};this.subsystems=[];this.broadphase.setWorld(this)};l.World.prototype=Object.create(w.prototype);var u,w;u={};w={};Object.keys(u).forEach(function(a){w[a]=u[a]});Object.defineProperties(l.World.prototype,w);var A,C,E,F;F={};A={};var H,I,M,N,X,Y,Z=new c,ia=new c,aa=new c,ba=new c,ca=new c,da=new c,ea=new c,fa=new c,ga=new c,M=new c,N=new c,X=new c,Y=new c,H=new c,I=new g;l.World.prototype.getContactMaterial=function(a,b){return this.mats2cmat.get(a.id,b.id)};l.World.prototype.numObjects=
function(){return this.bodies.length};l.World.prototype.collisionMatrixTick=function(){var a=this.collisionMatrixPrevious,b=this.collisionMatrix,c=this.bodies;a.copy(b);b.reset();for(var d=0,f=c.length;d!==f;d++){var g=c[d];g.wakeUp();for(var h=d+1;h<f;h++){var k=c[h];(g.sleepState===k.sleepState&&g.sleepState===k.SLEEPING||k.needsCollisionDetection(g))&&b.set(g,k,!0)}}};l.World.prototype.add=l.World.prototype.addBody=function(a){-1===this.bodies.indexOf(a)&&(a.index=this.bodies.length,this.bodies.push(a),
a.world=this,a.initPosition.copy(a.position),a.initVelocity.copy(a.velocity),a.timeLastSleepy=this.time,a.initAngularVelocity.copy(a.angularVelocity),a.initQuaternion.copy(a.quaternion),this.dispatchEvent({type:"addBody",body:a}))};l.World.prototype.addConstraint=function(a){this.constraints.push(a)};l.World.prototype.removeConstraint=function(a){a=this.constraints.indexOf(a);-1!==a&&this.constraints.splice(a,1)};l.World.prototype.remove=l.World.prototype.removeBody=function(a){a.world=null;var b=
this.bodies.indexOf(a);-1!==b&&(this.bodies.splice(b,1),this.dispatchEvent({type:"removeBody",body:a}))};l.World.prototype.addMaterial=function(a){this.materials.push(a)};l.World.prototype.addContactMaterial=function(a){this.contactmaterials.push(a);this.mats2cmat.set(a.materials[0].id,a.materials[1].id,a)};l.World.prototype.step=function(a,b,c){c=c||10;void 0===b&&(b=this.time,this.lastCallTime||(this.lastCallTime=b));var d=b-this.lastCallTime;this.lastCallTime=b;this.stepnumber++;if(this.doProfiling){var f=
Date.now();this.profile.solve=0;this.profile.makeContactConstraints=0;this.profile.broadphase=0;this.profile.integrate=0;this.profile.nearphase=0}for(var g=0,h=this;g<c&&!h.step(a);g++);this.time+=a;if(this.doProfiling)f=Date.now()-f,this.profile.total=f};var v={};l.World.prototype.step=function(a){var c=this.stepnumber,d=this.bodies,f=this.solver,g=this.gravity,h=this.doProfiling,p=this.profile,r=this.constraints,t=this.broadphase;A=a;this.contacts;this.frictionEquations;var u=d.length;this.preStep&&this.preStep.call(this);
t.collisionPairs(this,this.collisionMatrix,this.collisionMatrixPrevious);var w=this.contacts,B=this.mats2cmat;Object.keys(w).forEach(function(a){w[a].update()});for(var y=0;y<u;y++){var J=d[y];J.aabbNeedsUpdate&&J.computeAABB()}C=[];E=[];if(h)var L=Date.now();for(y=0;y<u;y++)J=d[y],J.sleepState===k.SLEEPING?J.angularVelocity.set(0,0,0):J.wakeUp();for(y=0;y<r.length;y++)L=r[y],L.update();if(h)p.makeContactConstraints+=Date.now()-L;for(y=0;y<r.length;y++){L=r[y];for(var N=0;N<L.equations.length;N++){var O=
L.equations[N];O.setSpookParams(L.contactEquationStiffness,L.contactEquationRelaxation,a)}}if(h)L=Date.now();for(y=0;y<u;y++){J=d[y];var P=J.force,Q=J.mass;P.x+=Q*g.x;P.y+=Q*g.y;P.z+=Q*g.z}f.solve(a,this);if(h)p.solve+=Date.now()-L;f.removeAllEquations();for(y=0;y<u;y++)J=d[y],J.integrate(a);if(h)L=Date.now();if(this.allowSleep)for(y=0;y<u;y++)d[y].sleepTick(this.time);if(h)p.integrate+=Date.now()-L;c% (this.quatNormalizeSkip+1)===0&&this.quatNormalizeFast?J.quaternion.normalizeFast():J.quaternion.normalize();
this.postStep&&this.postStep.call(this);this.emit("postStep");for(var R=0;R<this.subsystems.length;R++)this.subsystems[R].update();this.time+=a;this.stepnumber+=1;return!1};l.World.prototype.emit=w.prototype.emit;l.World.prototype.on=w.prototype.on;l.World.prototype.addEventListener=w.prototype.addEventListener;l.World.prototype.hasEventListener=w.prototype.hasEventListener;l.World.prototype.removeEventListener=w.prototype.removeEventListener;l.World.prototype.off=w.prototype.off;l.World.prototype.clearForces=
function(){for(var a=this.bodies,b=a.length,c=0;c!==b;c++){var d=a[c];d.force.set(0,0,0);d.torque.set(0,0,0)}};var u=function(a){this.name=a;this.id=u.idCounter++;this.friction=-1;this.restitution=-1};u.idCounter=0;var w=function(){function a(){this.id=a.idCounter++}a.idCounter=0;return a}(),p=function(){function a(){this.equations=[]}a.prototype.add=function(a){this.equations.push(a)};a.prototype.remove=function(a){a=this.equations.indexOf(a);-1!==a&&this.equations.splice(a,1)};a.prototype.removeAll=function(){this.equations.length=
0};a.prototype.solve=function(a,b){for(var c=0;c!==b.length;c++)b[c].updateSolveMassProperties();for(var d=this.equations,f=d.length,g=0;g!==f;g++)d[g].computeB(a);for(g=0;g!==f;g++)d[g].computeC();for(var h=0;h<this.iterations;h++)for(g=0;g!==f;g++){var k=d[g];k.computeGWlambda();var l=k.computeGlambda()*-this.k,n=k.maxForce,p=k.minForce;l=Math.max(p,Math.min(l,n));k.setSpookParams(k.a,k.b,1/a)}for(g=0;g!==f;g++)d[g].computeInvC(this.eps);for(h=0;h<this.iterations;h++){for(g=0;g!==f;g++)k=d[g],
l=-k.computeGWlambda(),k.minForce,k.maxForce,l=l,k.lamba+=l,k.lamba=Math.max(k.minForce,Math.min(k.lamba,k.maxForce));for(g=0;g!==f;g++)d[g].addToWlambda(d[g].lamba)}for(g=0;g!==f;g++){d=b[g];d.velocity.x+=d.vlambda.x;d.velocity.y+=d.vlambda.y;d.velocity.z+=d.vlambda.z;d.angularVelocity.x+=d.wlambda.x;d.angularVelocity.y+=d.wlambda.y;d.angularVelocity.z+=d.wlambda.z}};return a}(),A=function(a,b,c){c=c||{};this.id=A.idCounter++;this.minForce=void 0!==c.minForce?
c.minForce:-1E12;this.maxForce=void 0!==c.maxForce?c.maxForce:1E12;this.bi=a;this.bj=b;this.a=0;this.b=0;this.eps=0;this.jacobianElementA=new la;this.jacobianElementB=new la;this.enabled=!0;this.multiplier=0;this.setSpookParams(1E7,4,1/60)};A.idCounter=0;A.prototype.setSpookParams=function(a,b,c){var d=b,f=a,g=c;this.a=4/(d*d*(1+4*f*d*g));this.b=4*f*d*g/(1+4*f*d*g);this.eps=4/(d*d)};A.prototype.computeB=function(a,b,c){var d=this.computeGq(),f=this.computeGdot(),g=this.b;this.c=-(g*d+this.a*f+this.eps*
c)/b};A.prototype.computeGq=function(){var a=this.jacobianElementA,b=this.jacobianElementB,c=a.spatial,d=b.spatial,f=this.bi.position,g=this.bj.position;return c.dot(f)+d.dot(g)};A.prototype.computeGdot=function(a,b,c,d,f,g){a=this.jacobianElementA;b=this.jacobianElementB;c=this.bi;d=this.bj;f=c.velocity;g=c.angularVelocity;var h=d.velocity,k=d.angularVelocity;return a.spatial.dot(f)+a.rotational.dot(g)+b.spatial.dot(h)+b.rotational.dot(k)};A.prototype.computeC=function(){var a=this.jacobianElementA,
b=this.jacobianElementB,c=this.bi,d=this.bj;return c.invMass+d.invMass+c.invInertiaWorld.vmult(a.rotational).dot(a.rotational)+d.invInertiaWorld.vmult(b.rotational).dot(b.rotational)};A.prototype.computeGW=function(){var a=this.jacobianElementA,b=this.jacobianElementB,c=this.bi.velocity,d=this.bj.velocity,f=this.bi.angularVelocity,g=this.bj.angularVelocity;return this.gmult(a,c,f)+this.gmult(b,d,g)};A.prototype.computeGWlambda=function(){var a=this.jacobianElementA,b=this.jacobianElementB,c=this.bi.vlambda,
d=this.bj.vlambda,f=this.bi.wlambda,g=this.bj.wlambda;return this.gmult(a,c,f)+this.gmult(b,d,g)};A.prototype.gmult=function(a,b,d){return a.spatial.dot(b)+a.rotational.dot(d)};A.prototype.addToWlambda=function(a){var b=this.jacobianElementA,c=this.jacobianElementB,d=this.bi,f=this.bj,g=this.multiplier;d.vlambda.vadd(b.spatial.scale(d.invMass*g*a),d.vlambda);d.wlambda.vadd(d.invInertiaWorld.vmult(b.rotational).scale(g*a),d.wlambda);f.vlambda.vadd(c.spatial.scale(f.invMass*g*a),f.vlambda);f.wlambda.vadd(f.invInertiaWorld.vmult(c.rotational).scale(g*
a),f.wlambda)};A.prototype.computeInvC=function(a){return 1/(this.computeC()+a)},C=function(a,b,c){A.call(this,a,b,c);this.restitution=void 0!==c?c.restitution:0;this.ri=c.ri||new k;this.rj=c.rj||new k;this.penetration=c.penetration;this.contactNormal=c.contactNormal;this.friction=c.friction;this.contactEquationStiffness=c.contactEquationStiffness;this.contactEquationRelaxation=c.contactEquationRelaxation;this.frictionEquationStiffness=c.frictionEquationStiffness;this.frictionEquationRelaxation=
c.frictionEquationRelaxation;this.enabled=!0};C.prototype=new A;var la=function(){this.spatial=new c;this.rotational=new c},ma=new c,na=new c,oa=new c;C.prototype.computeB=function(a){var b=this.a,c=this.b,d=this.bi,f=this.bj,g=this.ri,h=this.rj,k=new c,l=new c;g.cross(this.contactNormal,k);h.cross(this.contactNormal,l);this.jacobianElementA.spatial.copy(this.contactNormal.negate());this.jacobianElementA.rotational.copy(k.negate());this.jacobianElementB.spatial.copy(this.contactNormal);this.jacobianElementB.rotational.copy(l);
this.g = this.computeGq() + this.penetration;
var gq = this.computeGq();
var GW = this.computeGW();
this.gb = -(c * gq - GW * b) / (b + 1 / (a * a)) };
C.prototype.getImpactVelocityAlongNormal=function(){var a=new c,b=new c,d=this.bi.getVelocityAtWorldPoint(this.ri,a),f=this.bj.getVelocityAtWorldPoint(this.rj,b);return d.vsub(f).dot(this.contactNormal)};E=function(a,b,c,d){A.call(this,a,b,c);this.ri=c.ri;this.rj=c.rj;this.slipForce=d;this.t=c.t;this.contactEquations=c.contactEquations;this.contactEquationStiffness=c.contactEquationStiffness;this.contactEquationRelaxation=c.contactEquationRelaxation;this.frictionEquationStiffness=c.frictionEquationStiffness;
this.frictionEquationRelaxation=c.frictionEquationRelaxation;this.enabled=!0};E.prototype=new A;E.prototype.computeB=function(a){var b=this.a,c=this.b,d=this.bi,f=this.bj,g=this.ri,h=this.rj,k=this.t,l=new c,p=new c;g.cross(k,l);h.cross(k,p);this.jacobianElementA.spatial.copy(k.negate());this.jacobianElementA.rotational.copy(l.negate());this.jacobianElementB.spatial.copy(k);this.jacobianElementB.rotational.copy(p);k=this.computeGq();this.g=this.computeGW();this.gb=-(c*k-this.g*b)/(b+1/(a*a))};var p=function(){},
ha=function(a){function b(a,b){return a.aabb.lowerBound[c]<b.aabb.lowerBound[c]?-1:1}w.apply(this);a=a||{};this.axis=void 0!==a.axis?a.axis:2;this.axisIndex=void 0!==a.axisIndex?a.axisIndex:2;this.dirty=!0;var c="xyz"[this.axis]};ha.prototype=new w;ha.prototype.collisionPairs=function(a,c,d){var f=a.bodies,g=f.length,h=this.axis,k=this.axisIndex;if(this.dirty)for(var l=0;l<g;l++)f[l].aabbNeedsUpdate&&f[l].computeAABB();f.sort(b);for(l=0;l<g;l++){for(var p=f[l],q=l+1;q<g;q++){var r=f[q];if(p.aabb.upperBound[h]<
r.aabb.lowerBound[h])break;p.aabb.overlaps(r)&&this.intersectionTest(p,r,c,d)}}this.dirty=!1};var ja=function(){function a(){this.matrix=[]}a.prototype.get=function(a,c){a=a.index;c=c.index;if(c>a){var d=c;c=a;a=d}return this.matrix[(a*(a+1)>>1)+c-1]};a.prototype.set=function(a,c,d){a=a.index;c=c.index;if(c>a){var f=c;c=a;a=f}d?this.matrix[(a*(a+1)>>1)+c-1]=!0:delete this.matrix[(a*(a+1)>>1)+c-1]};a.prototype.reset=function(){this.matrix.length=0};a.prototype.copy=function(a){this.matrix.length=
0;for(var c=0;c<a.matrix.length;c++)this.matrix[c]=a.matrix[c]};return a}(),ka=function(){function a(){this.table={}}a.prototype.get=function(a,c){if(a>c){var d=a;a=c;c=d}return this.table[a+"-"+c]};a.prototype.set=function(a,c,d){if(a>c){var f=a;a=c;c=f}this.table[a+"-"+c]=d};return a}(),p=function(){function a(b,c){b=b||{};var d=new k;d.set((b.maxX-b.minX)/2,(b.maxY-b.minY)/2,(b.maxZ-b.minZ)/2);var f=new k;f.set(b.minX,b.minY,b.minZ);b.transform.position.vadd(f,b.transform.position);this.halfExtents=
d;c=c||{};w.call(this,c);this.type=w.types.BOX}a.prototype=new w;a.prototype.constructor=a;a.prototype.calculateLocalInertia=function(a,b){b=b||new k;var c=this.halfExtents;b.x=(a/12)*(2*c.y*2*c.y+2*c.z*2*c.z);b.y=(a/12)*(2*c.x*2*c.x+2*c.z*2*c.z);b.z=(a/12)*(2*c.y*2*c.y+2*c.x*2*c.x);return b};a.prototype.getSideNormals=function(a,b){var c=this.halfExtents;a[0].set(1,0,0);a[1].set(0,1,0);a[2].set(0,0,1);a[3].set(-1,0,0);a[4].set(0,-1,0);a[5].set(0,0,-1);if(void 0!==b)for(var d=0;d!==a.length;d++)b.vmult(a[d],
a[d]);return a};a.prototype.volume=function(){return 8*this.halfExtents.x*this.halfExtents.y*this.halfExtents.z};var c,d;c=new k;d=new k;a.prototype.computeAABB=function(a,b,c){var d=this.halfExtents;a.lowerBound.set(b.x-d.x,b.y-d.y,b.z-d.z);a.upperBound.set(b.x+d.x,b.y+d.y,b.z+d.z)};var f;f=new k;a.prototype.calculateWorldAABB=function(a,b,c,d){var f=this.halfExtents;c.vmult(f,d);a.vsub(d,b);a.vadd(d,c)};var g,h,l,p,q,r,t,u,w,A,C,E,F,H;g=new k;h=new k;l=new k;p=new k;q=new k;r=new k;t=new k;u=new k;
w=new k;A=new k;C=new k;E=new k;F=new k;H=new k;a.prototype.updateBoundingSphereRadius=function(){this.boundingSphereRadius=this.halfExtents.length()};return a}(),w=function(){function a(){this.id=a.idCounter++}a.types={BOX:1,SPHERE:2,PLANE:4,PARTICLE:8,CYLINDER:16,CONVEXPOLYHEDRON:32,HEIGHTFIELD:64,TRIMESH:128};a.idCounter=0;a.prototype.updateBoundingSphereRadius=function(){throw"computeBoundingSphereRadius() not implemented for shape type "+this.type+"!";};a.prototype.volume=function(){throw"volume() not implemented for shape type "+
this.type+"!";};a.prototype.calculateLocalInertia=function(a,b){throw"calculateLocalInertia() not implemented for shape type "+this.type+"!";};return a}(),n=function(a,b,c){this.x=a;this.y=b;this.z=c;w.call(this,{type:w.types.PARTICLE})};n.prototype=new w;n.prototype.constructor=n;n.prototype.calculateLocalInertia=function(a,b){b=b||new c;b.set(0,0,0);return b};n.prototype.updateBoundingSphereRadius=function(){this.boundingSphereRadius=0};n.prototype.computeAABB=function(a,b){a.lowerBound.copy(b);
a.upperBound.copy(b)};l.AABB=q;l.ArrayCollisionMatrix=ja;l.Body=k;l.Box=p;l.Broadphase=function(){};l.Constraint=function(){};l.ContactEquation=C;l.ContactMaterial=t;l.Equation=A;l.Event=function(){};l.FrictionEquation=E;l.GridBroadphase=function(){};l.Heightfield=function(){};l.JacobianElement=la;l.Mat3=d;l.Material=u;l.NaiveBroadphase=ha;l.Narrowphase=function(){};l.ObjectCollisionMatrix=ka;l.Particle=n;l.Plane=function(){};l.Pool=p;l.Quaternion=g;l.Ray=function(){};l.RaycastResult=function(){};
l.RigidVehicle=function(){};l.RotationalEquation=function(){};l.SAPBroadphase=function(){};l.SPHSystem=function(){};l.Shape=w;l.Solver=p;l.Sphere=function(a){w.call(this,{type:w.types.SPHERE});this.radius=void 0!==a?a:1;this.updateBoundingSphereRadius()};l.Spring=h;l.Trimesh=function(){};l.Vec3=c;l.Vec3Pool=function(){};l.World=l.World});
